language: go
go:
- 1.4

env:
  global:
  - GOBIN=${HOME}/bin
  - PATH=${PATH}:${GOBIN}
  - secure: DmY1RzliNjQMkocUcTiSR76q6ViczW0xDTuHrTgIPvEQcLK2Zup1hg6CgQfy0RyzG2nm3rxHQHBG3KK2j/p23Yz40Qu5WzureBvf72qnp+81YpnqsHLjxUBC+DS2ggAWTaqafqC1sVwoUOt+hcH5RSUSa6zx53mPfYgyQc+8BRg=
install:
- mkdir ${HOME}/bin
- go get golang.org/x/tools/cmd/vet
- go get github.com/golang/lint/golint
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get github.com/modocache/gover
script:
- golint .
- go vet ./...
- go get -t ./...
- go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -i sh -c {}
- gover
- goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken=$COVERALLS_TOKEN
