language: go
go: 
 - 1.2
 - 1.3
 - release
 - tip
 
install:
 - go get code.google.com/p/go.tools/cmd/vet
 - go get -v ./...
 - go install -a -race std

script:
 - go tool vet -all .
 - go test -v -race ./...
