language: go
go: 
 - release
 - tip
 
install:
 - go get code.google.com/p/go.tools/cmd/vet
 - go get github.com/golang/lint/golint
 - go get -v ./...
 - go install -a -race std
 - export PATH=${PATH}:${HOME}/gopath/bin

script:
 - go tool vet -all .
 - golint .
 - go test -v -race ./...
