language: go
go: 
 - 1.2
 - 1.3
 - release
 - tip
 
install:
 - go get code.google.com/p/go.tools/cmd/vet
 - go get github.com/golang/lint/golint
 - go get -v ./...
 - go install -a -race std
 - go get code.google.com/p/go.tools/cmd/cover
 - go get github.com/mattn/goveralls
 - go get github.com/modocache/gover
 - export PATH=${PATH}:${HOME}/gopath/bin

script:
 - go tool vet -all .
 - golint .
 - go test -v -race ./... -coverprofile=.coverprofile
 - goveralls -coverprofile=.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
